version: "3"
services:
    db:
         image: mysql:5.7
         ports:
             - "3306:3306"
         environment:
             MYSQL_ROOT_PASSWORD: docker
             MYSQL_DATABASE: docker
             MYSQL_USER: docker
             MYSQL_PASSWORD: docker
    app:
       build:
           context: .
           dockerfile: Dockerfile
       volumes:
            - .:/app
       ports:
           - "8000:8000"
